### ISSUE TITLE
LEEF 1 VIDEO BIOMASS: mistake in calculation

### ISSUE THREAD

**Issue by duriah** [LEEF-UZH/LEEF.analysis#26]
While looking into the biomass calculation for LEEF2 I noticed that I made a mistake in the **_LEEF1_** biomass calculation in the videos. This resulted in an overestimation of ciliate biomass (by roughly half a magnitude on average). Sorry, this one is on me...

**The mistake**: for some reason, when calculating the biomass over the duration of the videos I did not take the average over the frames, but the sum. This means the longer the videos the higher the biomass estimate... (I did not make this mistake for the densities..)

In code, the line:
`summarize(biomass = sum(biomass, na.rm = T)) %>% #wrong` 
becomes
`summarize(biomass = sum(biomass*n_frames, na.rm = T)/(3*125)) %>% #correct`

As far as I can see the change is needed in the functions: 
```
LEEF_1_biomass_bemovi_25_non_cropped
LEEF_1_biomass_bemovi_25_cropped
LEEF_1_biomass_bemovi_25
LEEF_1_biomass_bemovi_16
```

The same goes for LEEF2 but I will provide the the code soon anyway.

Thanks @rkrug

**Comment by rkrug** [comment]
OK - reclassification is running. Will close when completed.
