### ISSUE TITLE
Further assessment of classification if deemed necessary? And if necessary further classification updates.Issue Title

### ISSUE THREAD

**Issue by rkrug** [LEEF-UZH/LEEF.analysis#7]

**Comment by duriah** [comment]
Pushed new LEEF2 video classifiers. Should improve classification of P. caudatum in the bottles with high temperature, high salt and high nutrient. Classification will still not be perfect but better. Remaining misclassification of Colpidium as P. caudatum can then be done manually. This update might worsen classifier performance elsewhere but I do not think so. To be monitored.

**Comment by rkrug** [comment]
New Parameter sets released (v2.3.7-LEEF-2) at https://github.com/LEEF-UZH/LEEF.parameter/releases/tag/v2.3.7-LEEF-2

**Comment by duriah** [comment]
It's possible that it is not the last classifier update, as we have to see how it performs and there might be an update for the flowcam as well. So it might be to early to close the issue

**Comment by duriah** [comment]
New Parameter sets released (v2.3.8-LEEF-2) at https://github.com/LEEF-UZH/LEEF.parameter/releases/tag/v2.3.8-LEEF-2

Includes new classifiers and changes to .yml files (species tracked).

hopefully final classifiers
